# Use an official Python runtime as the base image
FROM python:3.8-slim

# Set the working directory in the container to /app
WORKDIR /

# Copy the current directory (our Flask app) into the container
COPY . .

COPY requirements.txt /tmp/requirements.txt

# Install Flask and other dependencies
RUN pip install --no-cache-dir -r /tmp/requirements.txt

# Expose ports
EXPOSE 8010/tcp
EXPOSE 7010/tcp
EXPOSE 5001/tcp

# Run the command to start the Flask app
CMD ["python", "app.py", "&"]