# Use an official Python runtime as the base image
FROM python:3.8-slim

# Set the working directory in the container to /app
WORKDIR /

# Copy the current directory (our Flask app) into the container at /app
COPY . .

COPY requirements.txt /tmp/requirements.txt

# Install Flask and other dependencies
RUN pip install --no-cache-dir -r /tmp/requirements.txt

# Make port 5000 available for the app
EXPOSE 8015/tcp
EXPOSE 7015/tcp
EXPOSE 8415/tcp
EXPOSE 7615/tcp
EXPOSE 5004/tcp

# Run the command to start the Flask app
CMD ["python", "app.py", "&"]